<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AboutController extends Controller
{
     public function display(){
         $title ="About Us";
         $paragraph=" Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac turpis egestas sed tempus urna et pharetra. Elit ut aliquam purus sit amet luctus venenatis. Augue ut lectus arcu bibendum at varius. Pellentesque elit eget gravida cum sociis natoque. Accumsan in nisl nisi scelerisque eu ultrices vitae. Lectus proin nibh nisl condimentum. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Id semper risus in hendrerit gravida rutrum quisque. Velit euismod in pellentesque massa. Facilisi etiam dignissim diam quis enim lobortis. Maecenas volutpat blandit aliquam etiam. Venenatis urna cursus eget nunc. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Nec ullamcorper sit amet risus nullam eget felis eget. Platea dictumst vestibulum rhoncus est pellentesque. Id aliquet lectus proin nibh nisl condimentum.

Odio aenean sed adipiscing diam donec adipiscing. In pellentesque massa placerat duis ultricies lacus sed turpis. Tincidunt vitae semper quis lectus nulla at volutpat diam. Praesent semper feugiat nibh sed pulvinar proin gravida. Sit amet consectetur adipiscing elit pellentesque. Posuere lorem ipsum dolor sit amet consectetur adipiscing. Velit aliquet sagittis id consectetur purus ut faucibus. Pellentesque sit amet porttitor eget dolor morbi. Urna duis convallis convallis tellus id interdum. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Dui sapien eget mi proin sed. Aliquet risus feugiat in ante. Et ultrices neque ornare aenean euismod elementum. Pellentesque habitant morbi tristique senectus et. Sed risus ultricies tristique nulla aliquet enim. Urna molestie at elementum eu. Fringilla urna porttitor rhoncus dolor. Neque viverra justo nec ultrices dui sapien eget.

Aliquam nulla facilisi cras fermentum odio eu feugiat. Vitae suscipit tellus mauris a diam. Fusce ut placerat orci nulla pellentesque dignissim enim sit. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Vestibulum lorem sed risus ultricies tristique nulla. Dignissim sodales ut eu sem integer vitae. Vel facilisis volutpat est velit egestas dui. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tincidunt augue interdum velit euismod. Quam quisque id diam vel quam elementum pulvinar etiam. Sit amet cursus sit amet dictum sit. Condimentum vitae sapien pellentesque habitant morbi. Nunc congue nisi vitae suscipit tellus mauris a diam. Id venenatis a condimentum vitae sapien pellentesque habitant. Nam aliquam sem et tortor consequat id porta nibh.

Eu scelerisque felis imperdiet proin fermentum leo vel orci. Accumsan lacus vel facilisis volutpat est velit. Eget est lorem ipsum dolor sit. Suspendisse ultrices gravida dictum fusce ut placerat orci. Vel eros donec ac odio tempor orci dapibus ultrices in. Velit sed ullamcorper morbi tincidunt ornare massa. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Etiam non quam lacus suspendisse faucibus interdum posuere lorem. Sit amet est placerat in egestas erat imperdiet. Pellentesque habitant morbi tristique senectus et netus et malesuada. In aliquam sem fringilla ut. Morbi tristique senectus et netus et malesuada fames. Tristique magna sit amet purus gravida. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Amet cursus sit amet dictum sit.

Nunc eget lorem dolor sed viverra ipsum nunc aliquet. Urna condimentum mattis pellentesque id nibh tortor id. Non sodales neque sodales ut etiam sit amet nisl purus. Pharetra massa massa ultricies mi quis. Dui vivamus arcu felis bibendum ut tristique et egestas. Integer quis auctor elit sed vulputate mi. Amet dictum sit amet justo donec enim diam vulputate ut. Faucibus interdum posuere lorem ipsum dolor sit amet. Eu scelerisque felis imperdiet proin fermentum leo vel. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Volutpat blandit aliquam etiam erat velit. In arcu cursus euismod quis viverra nibh. Sapien eget mi proin sed libero enim sed. Bibendum enim facilisis gravida neque convallis. Nunc id cursus metus aliquam. Mauris pharetra et ultrices neque ornare aenean. Commodo nulla facilisi nullam vehicula. Donec enim diam vulputate ut pharetra sit.";
             return view('about', compact('title', 'paragraph'));
     }
}
